#!/bin/bash

NAME="$1"
ORG="nknapp"
unset DISPLAY

if [ -z "${NAME}" ] ; then
    echo Usage "$0" repo-name
    exit 1
fi



# Create from template
khaos create nils "$NAME"

# Create github repo
gh re -N "$NAME" -O "$ORG"

# Initialize git
cd "$1"
git init
git remote add origin git@github.com:"$ORG"/"$NAME".git
# Add all files to the repository
git add .
git commit -m "Initial check-in"
git push -u origin master