#!/bin/bash

. ~/.gh-token
export GH_TOKEN

USER="nknapp"

if [ -z "${NAME}" ] ; then
    echo Usage "$0" repo-name
    echo
    exit 1
fi


# Create from template
khaos create nils "$NAME"

cd "$1" || exit 1

push-to-github